# Generated by Django 2.2.1 on 2019-06-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='c',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='q_no',
            field=models.IntegerField(default=1),
        ),
    ]
